
clean:
	rm -rf xst __projnav _ngo
	rm -f *.ncd *.par *.pcf *.bld *.log *.bit *.ngc *.mrp *.bgn *.cmd_log *.drc
	rm -f *.ngd *.lso *.twr *.stx *.syr *~ *.pad *.pad_txt *.twx *.ngm *.csv
	rm -f *.ut *.nc1 *.ngr *.placed_ncd_tracker *.routed_ncd_tracker *.prj 
	rm -f *.untf *.xpi *_pad.txt _impact.cmd transcript *.dhp
