
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 9.2.02 EDK_Jm_SP2.3
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xtft.h"

/*
* The configuration table for devices
*/

XTft_Config XTft_ConfigTable[] =
{
	{
		XPAR_VGA_FRAMEBUFFER_DEVICE_ID,
		XPAR_VGA_FRAMEBUFFER_DEFAULT_TFT_BASE_ADDR
	}
};


