#################################################################
# Makefile generated by Xilinx Platform Studio 
# Project:/home/rmeiche/Xilinx/EDK-projects/XUP_Ref_MPMC_10.1/system.xmp
#
# WARNING : This file will be re-generated every time a command
# to run a make target is invoked. So, any changes made to this  
# file manually, will be lost when make is invoked next. 
#################################################################

XILINX_EDK_DIR = /Xilinx/10.1/EDK
NON_CYG_XILINX_EDK_DIR = /Xilinx/10.1/EDK

SYSTEM = system

MHSFILE = system.mhs

MSSFILE = system.mss

FPGA_ARCH = virtex2p

DEVICE = xc2vp30ff896-7

LANGUAGE = vhdl

SEARCHPATHOPT = 

SUBMODULE_OPT = 

PLATGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(SUBMODULE_OPT)

LIBGEN_OPTIONS = -mhs $(MHSFILE) -p $(DEVICE) $(SEARCHPATHOPT)

VPGEN_OPTIONS = -p $(DEVICE) $(SEARCHPATHOPT)

MANAGE_FASTRT_OPTIONS = -reduce_fanout no

OBSERVE_PAR_OPTIONS = -error yes

CALIBRATION_OUTPUT_DIR = calibration
CALIBRATION_OUTPUT = $(CALIBRATION_OUTPUT_DIR)/executable.elf

MICROBLAZE_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop.elf
PPC405_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc405/ppc_bootloop.elf
PPC440_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc440/ppc440_bootloop.elf
BOOTLOOP_DIR = bootloops

PPC405_0_BOOTLOOP = $(BOOTLOOP_DIR)/ppc405_0.elf

BRAMINIT_ELF_FILES =  $(CALIBRATION_OUTPUT) 
BRAMINIT_ELF_FILE_ARGS =   -pe ppc405_0 $(CALIBRATION_OUTPUT) 

ALL_USER_ELF_FILES = $(CALIBRATION_OUTPUT) 

SIM_CMD = vsim

BEHAVIORAL_SIM_SCRIPT = simulation/behavioral/$(SYSTEM)_setup.do

STRUCTURAL_SIM_SCRIPT = simulation/structural/$(SYSTEM)_setup.do

TIMING_SIM_SCRIPT = simulation/timing/$(SYSTEM)_setup.do

DEFAULT_SIM_SCRIPT = $(BEHAVIORAL_SIM_SCRIPT)

MIX_LANG_SIM_OPT = -mixed yes

SIMGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(BRAMINIT_ELF_FILE_ARGS) $(MIX_LANG_SIM_OPT)  -s mti


LIBRARIES =  \
       ppc405_0/lib/libxil.a 
VPEXEC = virtualplatform/vpexec

LIBSCLEAN_TARGETS = ppc405_0_libsclean 

PROGRAMCLEAN_TARGETS = calibration_programclean 

CORE_STATE_DEVELOPMENT_FILES = 

WRAPPER_NGC_FILES = implementation/ppc405_0_wrapper.ngc \
implementation/jtagppc_cntlr_0_wrapper.ngc \
implementation/plb0_wrapper.ngc \
implementation/xps_bram_if_cntlr_1_wrapper.ngc \
implementation/plb_bram_if_cntlr_1_bram_wrapper.ngc \
implementation/rs232_uart_wrapper.ngc \
implementation/ddr_sdram_wrapper.ngc \
implementation/dcm_phaseshift_wrapper.ngc \
implementation/ppc405_0_iplb1_wrapper.ngc \
implementation/ppc405_0_dplb1_wrapper.ngc \
implementation/clock_generator_0_wrapper.ngc \
implementation/proc_sys_reset_0_wrapper.ngc

POSTSYN_NETLIST = implementation/$(SYSTEM).ngc

SYSTEM_BIT = implementation/$(SYSTEM).bit

DOWNLOAD_BIT = implementation/download.bit

SYSTEM_ACE = implementation/$(SYSTEM).ace

UCF_FILE = data/system.ucf

BMM_FILE = implementation/$(SYSTEM).bmm

BITGEN_UT_FILE = etc/bitgen.ut

XFLOW_OPT_FILE = etc/fast_runtime.opt
XFLOW_DEPENDENCY = __xps/xpsxflow.opt $(XFLOW_OPT_FILE)

XPLORER_DEPENDENCY = __xps/xplorer.opt
XPLORER_OPTIONS = -p $(DEVICE) -uc $(SYSTEM).ucf -bm $(SYSTEM).bmm -max_runs 7

FPGA_IMP_DEPENDENCY = $(BMM_FILE) $(POSTSYN_NETLIST) $(UCF_FILE) $(XFLOW_DEPENDENCY)

#################################################################
# SOFTWARE APPLICATION CALIBRATION
#################################################################

CALIBRATION_SOURCES = calibration/calibration.c 

CALIBRATION_HEADERS = 

CALIBRATION_CC = powerpc-eabi-gcc
CALIBRATION_CC_SIZE = powerpc-eabi-size
CALIBRATION_CC_OPT = -O2
CALIBRATION_CFLAGS = 
CALIBRATION_CC_SEARCH = # -B
CALIBRATION_LIBPATH = -L./ppc405_0/lib/ # -L
CALIBRATION_INCLUDES = -I./ppc405_0/include/ # -I
CALIBRATION_LFLAGS = # -l
CALIBRATION_LINKER_SCRIPT = calibration/calibration_linker_script.ld
CALIBRATION_LINKER_SCRIPT_FLAG = -Wl,-T -Wl,$(CALIBRATION_LINKER_SCRIPT) 
CALIBRATION_CC_DEBUG_FLAG =  -g 
CALIBRATION_CC_PROFILE_FLAG = # -pg
CALIBRATION_CC_GLOBPTR_FLAG= # -msdata=eabi
CALIBRATION_CC_INFERRED_FLAGS= 
CALIBRATION_CC_START_ADDR_FLAG=  #  # -Wl,-defsym -Wl,_START_ADDR=
CALIBRATION_CC_STACK_SIZE_FLAG=  #  # -Wl,-defsym -Wl,_STACK_SIZE=
CALIBRATION_CC_HEAP_SIZE_FLAG=  #  # -Wl,-defsym -Wl,_HEAP_SIZE=
CALIBRATION_OTHER_CC_FLAGS= $(CALIBRATION_CC_GLOBPTR_FLAG)  \
                  $(CALIBRATION_CC_START_ADDR_FLAG) $(CALIBRATION_CC_STACK_SIZE_FLAG) $(CALIBRATION_CC_HEAP_SIZE_FLAG)  \
                  $(CALIBRATION_CC_INFERRED_FLAGS)  \
                  $(CALIBRATION_LINKER_SCRIPT_FLAG) $(CALIBRATION_CC_DEBUG_FLAG) $(CALIBRATION_CC_PROFILE_FLAG) 
