
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 9.2.02 EDK_Jm_SP2.3
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_LEDS_4BIT_DEVICE_ID,
		XPAR_LEDS_4BIT_BASEADDR,
		XPAR_LEDS_4BIT_INTERRUPT_PRESENT,
		XPAR_LEDS_4BIT_IS_DUAL
	},
	{
		XPAR_DIPSWS_4BIT_DEVICE_ID,
		XPAR_DIPSWS_4BIT_BASEADDR,
		XPAR_DIPSWS_4BIT_INTERRUPT_PRESENT,
		XPAR_DIPSWS_4BIT_IS_DUAL
	},
	{
		XPAR_PUSHBUTTONS_5BIT_DEVICE_ID,
		XPAR_PUSHBUTTONS_5BIT_BASEADDR,
		XPAR_PUSHBUTTONS_5BIT_INTERRUPT_PRESENT,
		XPAR_PUSHBUTTONS_5BIT_IS_DUAL
	}
};


