
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 9.2.02 EDK_Jm_SP2.3
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xuartns550.h"

/*
* The configuration table for devices
*/

XUartNs550_Config XUartNs550_ConfigTable[] =
{
	{
		XPAR_RS232_UART_1_DEVICE_ID,
		XPAR_RS232_UART_1_BASEADDR,
		XPAR_XUARTNS550_CLOCK_HZ
	}
};


