
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 9.2.02 EDK_Jm_SP2.3
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xhwicap.h"

/*
* The configuration table for devices
*/

XHwIcap_Config XHwIcap_ConfigTable[] =
{
	{
		XPAR_OPB_HWICAP_0_DEVICE_ID,
		XPAR_OPB_HWICAP_0_BASEADDR
	}
};


