
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 9.2.02 EDK_Jm_SP2.3
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xmpmc.h"

/*
* The configuration table for devices
*/

XMpmc_Config XMpmc_ConfigTable[] =
{
	{
		XPAR_DDR_SDRAM_DEVICE_ID,
		XPAR_DDR_SDRAM_MPMC_CTRL_BASEADDR,
		XPAR_DDR_SDRAM_INCLUDE_ECC_SUPPORT
	}
};


