
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 8.2.02 EDK_Im_Sp2.4
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver configuration
*
*******************************************************************/

#include <pkgconf/hal_microblaze_platform.h>
#include "xemaclite.h"

/*
* The configuration table for devices
*/

XEmacLite_Config XEmacLite_ConfigTable[] =
{
	{
		0,
		MON_EMACLITE_BASE,
		MON_EMACLITE_TX_PING_PONG,
		MON_EMACLITE_RX_PING_PONG
	}
};


