#!/usr/bin/env bash
#
# common tools for testing
# stolen from CentOS /etc/init.d/functions
#

# Make sure umask is sane
umask 022

# Get a sane screen width
[ -z "${COLUMNS:-}" ] && COLUMNS=80

[ -z "${CONSOLETYPE:-}" ] && CONSOLETYPE="`/sbin/consoletype`"

# This all seem confusing? Look in /etc/sysconfig/init,
# or in /usr/doc/initscripts-*/sysconfig.txt
BOOTUP=color
RES_COL=60
MOVE_TO_COL="echo -en \\033[${RES_COL}G"
SETCOLOR_SUCCESS="echo -en \\033[1;32m"
SETCOLOR_FAILURE="echo -en \\033[1;31m"
SETCOLOR_WARNING="echo -en \\033[1;33m"
SETCOLOR_NORMAL="echo -en \\033[0;39m"
LOGLEVEL=1
if [ "$CONSOLETYPE" = "serial" ]; then
  BOOTUP=serial
  MOVE_TO_COL=
  SETCOLOR_SUCCESS=
  SETCOLOR_FAILURE=
  SETCOLOR_WARNING=
  SETCOLOR_NORMAL=
fi

echo_success() {
    echo -n "$TEST"
    [ "$BOOTUP" = "color" ] && $MOVE_TO_COL
    echo -n "[  "
    [ "$BOOTUP" = "color" ] && $SETCOLOR_SUCCESS
    echo -n $"OK"
    [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
    echo "  ]"
    return 0
}

echo_failure() {
    echo -n "$TEST"
    [ "$BOOTUP" = "color" ] && $MOVE_TO_COL
    echo -n "["
    [ "$BOOTUP" = "color" ] && $SETCOLOR_FAILURE
    echo -n $"FAILED"
    [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
    echo "]"
    return 1
}

echo_passed() {
    echo -n "$TEST"
    [ "$BOOTUP" = "color" ] && $MOVE_TO_COL
    echo -n "["
    [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
    echo -n $"PASSED"
    [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
    echo "]"
    return 1
}

echo_warning() {
    echo -n "$TEST"
    [ "$BOOTUP" = "color" ] && $MOVE_TO_COL
    echo -n "["
    [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
    echo -n $"WARNING"
    [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
    echo "]"
    return 1
}

# returns OK if $1 contains $2
strstr() {
  [ "${1#*$2*}" = "$1" ] && return 1
  return 0
}

# run diff on vhdl file after stripping comments, leading/trailing spaces
# and empty lines
diff_vhdl() {
    A="/tmp/$(basename $1).stripped"
    B="/tmp/$(basename $2).stripped"
    perl -p -e "s/--.*//; s/^\s+//; s/\s+$/\n/" "$1" > "$A"
    perl -p -e "s/--.*//; s/^\s+//; s/\s+$/\n/" "$2" > "$B"
    diff -q "$A" "$B" &> /dev/null
    retval=$?
    rm "$A" "$B"
    return $retval
}