
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 8.2.02 EDK_Im_Sp2.4
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver configuration
*
*******************************************************************/

#include <pkgconf/hal_microblaze_platform.h>
#include "xuartns550.h"

/*
* The configuration table for devices
*/

XUartNs550_Config XUartNs550_ConfigTable[] =
{
	{
		0,
		MON_UART16550_0_BASE,
		MON_CPU_SYSTEM_CLK
	}
};


