
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 9.2.02 EDK_Jm_SP2.3
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver parameters
*
*******************************************************************/

/* Definitions for driver TFT_REF */
#define XPAR_XTFT_NUM_INSTANCES 1

/* Definitions for peripheral VGA_FRAMEBUFFER */
#define XPAR_VGA_FRAMEBUFFER_DCR_BASEADDR 0x00000000
#define XPAR_VGA_FRAMEBUFFER_DCR_HIGHADDR 0x00000001
#define XPAR_VGA_FRAMEBUFFER_DEVICE_ID 0
#define XPAR_VGA_FRAMEBUFFER_DEFAULT_TFT_BASE_ADDR 0x1EE00000


/******************************************************************/

/* Definitions for driver DDR */
#define XPAR_XDDR_NUM_INSTANCES 1

/* Definitions for peripheral DDR_512MB_64MX64_RANK2_ROW13_COL10_CL2_5 */
#define XPAR_DDR_512MB_64MX64_RANK2_ROW13_COL10_CL2_5_ECC_BASEADDR 0xFFFFFFFF
#define XPAR_DDR_512MB_64MX64_RANK2_ROW13_COL10_CL2_5_ECC_HIGHADDR 0x00000000
#define XPAR_DDR_512MB_64MX64_RANK2_ROW13_COL10_CL2_5_DEVICE_ID 0
#define XPAR_DDR_512MB_64MX64_RANK2_ROW13_COL10_CL2_5_INCLUDE_ECC_INTR 0


/******************************************************************/

/* Definitions for peripheral DDR_512MB_64MX64_RANK2_ROW13_COL10_CL2_5 */
#define XPAR_DDR_512MB_64MX64_RANK2_ROW13_COL10_CL2_5_MEM0_BASEADDR 0x00000000
#define XPAR_DDR_512MB_64MX64_RANK2_ROW13_COL10_CL2_5_MEM0_HIGHADDR 0x0FFFFFFF
#define XPAR_DDR_512MB_64MX64_RANK2_ROW13_COL10_CL2_5_MEM1_BASEADDR 0x10000000
#define XPAR_DDR_512MB_64MX64_RANK2_ROW13_COL10_CL2_5_MEM1_HIGHADDR 0x1FFFFFFF

/******************************************************************/


/* Definitions for peripheral PLB_BRAM_IF_CNTLR_1 */
#define XPAR_PLB_BRAM_IF_CNTLR_1_BASEADDR 0xffffc000
#define XPAR_PLB_BRAM_IF_CNTLR_1_HIGHADDR 0xffffffff


/******************************************************************/

/* Definitions for driver OPBARB */
#define XPAR_XOPBARB_NUM_INSTANCES 1

/* Definitions for peripheral OPB */
#define XPAR_OPB_BASEADDR 0xFFFFFFFF
#define XPAR_OPB_HIGHADDR 0x00000000
#define XPAR_OPB_DEVICE_ID 0
#define XPAR_OPB_NUM_MASTERS 1


/******************************************************************/

/* Definitions for driver OPB_ONEWIRE */
#define XPAR_OPB_ONEWIRE_NUM_INSTANCES 1

/* Definitions for peripheral ONEWIRE_0 */
#define XPAR_ONEWIRE_0_BASEADDR 0x7A200000
#define XPAR_ONEWIRE_0_HIGHADDR 0x7A20FFFF


/******************************************************************/

/* Definitions for driver UARTNS550 */
#define XPAR_XUARTNS550_NUM_INSTANCES 1
#define XPAR_XUARTNS550_CLOCK_HZ 100000000

/* Definitions for peripheral RS232_UART_1 */
#define XPAR_RS232_UART_1_DEVICE_ID 0
#define XPAR_RS232_UART_1_BASEADDR 0x40400000
#define XPAR_RS232_UART_1_HIGHADDR 0x4040FFFF


/******************************************************************/


/* Canonical definitions for peripheral RS232_UART_1 */
#define XPAR_UARTNS550_0_CLOCK_FREQ_HZ 100000000
#define XPAR_UARTNS550_0_DEVICE_ID XPAR_RS232_UART_1_DEVICE_ID
#define XPAR_UARTNS550_0_BASEADDR 0x40400000
#define XPAR_UARTNS550_0_HIGHADDR 0x4040FFFF


/******************************************************************/

/* Definitions for driver EMAC */
#define XPAR_XEMAC_NUM_INSTANCES 1

/* Definitions for peripheral ETHERNET_MAC */
#define XPAR_ETHERNET_MAC_BASEADDR 0x50400000
#define XPAR_ETHERNET_MAC_HIGHADDR 0x5040FFFF
#define XPAR_ETHERNET_MAC_DEVICE_ID 0
#define XPAR_ETHERNET_MAC_ERR_COUNT_EXIST 1
#define XPAR_ETHERNET_MAC_DMA_PRESENT 1
#define XPAR_ETHERNET_MAC_MII_EXIST 1


/******************************************************************/

#define XPAR_XSYSACE_MEM_WIDTH 16
/* Definitions for driver SYSACE */
#define XPAR_XSYSACE_NUM_INSTANCES 1

/* Definitions for peripheral SYSACE_COMPACTFLASH */
#define XPAR_SYSACE_COMPACTFLASH_DEVICE_ID 0
#define XPAR_SYSACE_COMPACTFLASH_BASEADDR 0x41800000
#define XPAR_SYSACE_COMPACTFLASH_HIGHADDR 0x4180FFFF
#define XPAR_SYSACE_COMPACTFLASH_MEM_WIDTH 16


/******************************************************************/


/* Canonical definitions for peripheral SYSACE_COMPACTFLASH */
#define XPAR_SYSACE_0_DEVICE_ID XPAR_SYSACE_COMPACTFLASH_DEVICE_ID
#define XPAR_SYSACE_0_BASEADDR 0x41800000
#define XPAR_SYSACE_0_HIGHADDR 0x4180FFFF
#define XPAR_SYSACE_0_MEM_WIDTH 16


/******************************************************************/

/* Definitions for driver GPIO */
#define XPAR_XGPIO_NUM_INSTANCES 3

/* Definitions for peripheral LEDS_4BIT */
#define XPAR_LEDS_4BIT_BASEADDR 0x40000000
#define XPAR_LEDS_4BIT_HIGHADDR 0x4000FFFF
#define XPAR_LEDS_4BIT_DEVICE_ID 0
#define XPAR_LEDS_4BIT_INTERRUPT_PRESENT 0
#define XPAR_LEDS_4BIT_IS_DUAL 0


/* Definitions for peripheral DIPSWS_4BIT */
#define XPAR_DIPSWS_4BIT_BASEADDR 0x40020000
#define XPAR_DIPSWS_4BIT_HIGHADDR 0x4002FFFF
#define XPAR_DIPSWS_4BIT_DEVICE_ID 1
#define XPAR_DIPSWS_4BIT_INTERRUPT_PRESENT 0
#define XPAR_DIPSWS_4BIT_IS_DUAL 0


/* Definitions for peripheral PUSHBUTTONS_5BIT */
#define XPAR_PUSHBUTTONS_5BIT_BASEADDR 0x40040000
#define XPAR_PUSHBUTTONS_5BIT_HIGHADDR 0x4004FFFF
#define XPAR_PUSHBUTTONS_5BIT_DEVICE_ID 2
#define XPAR_PUSHBUTTONS_5BIT_INTERRUPT_PRESENT 1
#define XPAR_PUSHBUTTONS_5BIT_IS_DUAL 0


/******************************************************************/

/* Definitions for driver PS2_REF */
#define XPAR_XPS2_NUM_INSTANCES 1

/* Definitions for peripheral PS2_PORTS */
#define XPAR_PS2_PORTS_BASEADDR 0x7A400000
#define XPAR_PS2_PORTS_HIGHADDR 0x7A40FFFF
#define XPAR_PS2_PORTS_DEVICE_ID 0


/******************************************************************/

#define XPAR_INTC_MAX_NUM_INTR_INPUTS 7
#define XPAR_XINTC_HAS_IPR 1
#define XPAR_XINTC_USE_DCR 0
/* Definitions for driver INTC */
#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral OPB_INTC_0 */
#define XPAR_OPB_INTC_0_DEVICE_ID 0
#define XPAR_OPB_INTC_0_BASEADDR 0x41200000
#define XPAR_OPB_INTC_0_HIGHADDR 0x4120FFFF
#define XPAR_OPB_INTC_0_KIND_OF_INTR 0x00000000


/******************************************************************/

#define XPAR_INTC_SINGLE_BASEADDR 0x41200000
#define XPAR_INTC_SINGLE_HIGHADDR 0x4120FFFF
#define XPAR_INTC_SINGLE_DEVICE_ID XPAR_OPB_INTC_0_DEVICE_ID
#define XPAR_SYSTEM_FPGA_0_ETHERNET_MAC_PHY_MII_INT_N_PIN_MASK 0X000001
#define XPAR_OPB_INTC_0_SYSTEM_FPGA_0_ETHERNET_MAC_PHY_MII_INT_N_PIN_INTR 0
#define XPAR_ETHERNET_MAC_IP2INTC_IRPT_MASK 0X000002
#define XPAR_OPB_INTC_0_ETHERNET_MAC_IP2INTC_IRPT_INTR 1
#define XPAR_SYSACE_COMPACTFLASH_SYSACE_IRQ_MASK 0X000004
#define XPAR_OPB_INTC_0_SYSACE_COMPACTFLASH_SYSACE_IRQ_INTR 2
#define XPAR_RS232_UART_1_IP2INTC_IRPT_MASK 0X000008
#define XPAR_OPB_INTC_0_RS232_UART_1_IP2INTC_IRPT_INTR 3
#define XPAR_PUSHBUTTONS_5BIT_IP2INTC_IRPT_MASK 0X000010
#define XPAR_OPB_INTC_0_PUSHBUTTONS_5BIT_IP2INTC_IRPT_INTR 4
#define XPAR_PS2_PORTS_SYS_INTR2_MASK 0X000020
#define XPAR_OPB_INTC_0_PS2_PORTS_SYS_INTR2_INTR 5
#define XPAR_PS2_PORTS_SYS_INTR1_MASK 0X000040
#define XPAR_OPB_INTC_0_PS2_PORTS_SYS_INTR1_INTR 6

/******************************************************************/


/* Canonical definitions for peripheral OPB_INTC_0 */
#define XPAR_INTC_0_DEVICE_ID XPAR_OPB_INTC_0_DEVICE_ID
#define XPAR_INTC_0_BASEADDR 0x41200000
#define XPAR_INTC_0_HIGHADDR 0x4120FFFF
#define XPAR_INTC_0_KIND_OF_INTR 0x00000000

#define XPAR_INTC_0_EMAC_0_VEC_ID XPAR_OPB_INTC_0_ETHERNET_MAC_IP2INTC_IRPT_INTR
#define XPAR_INTC_0_SYSACE_0_VEC_ID XPAR_OPB_INTC_0_SYSACE_COMPACTFLASH_SYSACE_IRQ_INTR
#define XPAR_INTC_0_UARTNS550_0_VEC_ID XPAR_OPB_INTC_0_RS232_UART_1_IP2INTC_IRPT_INTR
#define XPAR_INTC_0_GPIO_2_VEC_ID XPAR_OPB_INTC_0_PUSHBUTTONS_5BIT_IP2INTC_IRPT_INTR
#define XPAR_INTC_0_PS2_1_SYS_INTR2_VEC_ID XPAR_OPB_INTC_0_PS2_PORTS_SYS_INTR2_INTR
#define XPAR_INTC_0_PS2_0_SYS_INTR1_VEC_ID XPAR_OPB_INTC_0_PS2_PORTS_SYS_INTR1_INTR

/******************************************************************/

/* Definitions for driver HWICAP */
#define XPAR_XHWICAP_NUM_INSTANCES 1

/* Definitions for peripheral OPB_HWICAP_0 */
#define XPAR_OPB_HWICAP_0_BASEADDR 0x51000000
#define XPAR_OPB_HWICAP_0_HIGHADDR 0x510FFFFF
#define XPAR_OPB_HWICAP_0_DEVICE_ID 0


/******************************************************************/

#define XPAR_CPU_PPC405_CORE_CLOCK_FREQ_HZ 300000000

/******************************************************************/

#define XPAR_CPU_ID 0
#define XPAR_PPC405_ID 0
#define XPAR_PPC405_CORE_CLOCK_FREQ_HZ 300000000
#define XPAR_PPC405_ISOCM_DCR_BASEADDR 0x00000010
#define XPAR_PPC405_ISOCM_DCR_HIGHADDR 0x00000013
#define XPAR_PPC405_DSOCM_DCR_BASEADDR 0x00000020
#define XPAR_PPC405_DSOCM_DCR_HIGHADDR 0x00000023
#define XPAR_PPC405_DISABLE_OPERAND_FORWARDING 1
#define XPAR_PPC405_DETERMINISTIC_MULT 0
#define XPAR_PPC405_MMU_ENABLE 1
#define XPAR_PPC405_DCR_RESYNC 2
#define XPAR_PPC405_HW_VER "2.00.c"

/******************************************************************/

